// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuc6DJaUyGmGeXGvdBgJJxdtM-uisbpA',
    appId: '1:463305592509:web:3de631fd769b995962f1d4',
    messagingSenderId: '463305592509',
    projectId: 'kalmar-driver-app',
    authDomain: 'kalmar-driver-app.firebaseapp.com',
    storageBucket: 'kalmar-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZm9dmAPlJWjX7tAgT4NfrxJ44a_s4po',
    appId: '1:463305592509:android:6509c9d21eec0abe62f1d4',
    messagingSenderId: '463305592509',
    projectId: 'kalmar-driver-app',
    storageBucket: 'kalmar-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARuw4Cu_T2gcfCL048DK1TV5iS7RK1chU',
    appId: '1:463305592509:ios:53d4547a95d7e3b262f1d4',
    messagingSenderId: '463305592509',
    projectId: 'kalmar-driver-app',
    storageBucket: 'kalmar-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.kalmarDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARuw4Cu_T2gcfCL048DK1TV5iS7RK1chU',
    appId: '1:463305592509:ios:53d4547a95d7e3b262f1d4',
    messagingSenderId: '463305592509',
    projectId: 'kalmar-driver-app',
    storageBucket: 'kalmar-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.kalmarDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRuc6DJaUyGmGeXGvdBgJJxdtM-uisbpA',
    appId: '1:463305592509:web:67462e1b563accdb62f1d4',
    messagingSenderId: '463305592509',
    projectId: 'kalmar-driver-app',
    authDomain: 'kalmar-driver-app.firebaseapp.com',
    storageBucket: 'kalmar-driver-app.firebasestorage.app',
  );
}
